### PR TITLE
MAKE ACID GREAT AGAIN 

### PR DESCRIPTION
**Pull request by newguywhoislearning**
Buffs both sacid and pacid, hoping to make them great again!

### CODE REVIEW

**Comment by ninjacha** [comment]
what the fuck is this
you just added the old toxins

**Comment by ninjacha** [comment]
also get good nerd, wait til octareen merges my travis fix before submitting a pr

**Comment by ninjacha** [comment]
oh. I guess github website PR shit does adding not changes?

hmm

**Comment by newguywhoislearning** [comment]
-what the fuck is this
-you just added the old toxins
No, I buffed pacid and sacid's item destruction power.
-also get good nerd, wait til octareen merges my travis fix before submitting a pr
I've really have no idea how github works.
-oh. I guess github website PR shit does adding not changes?
?

**Comment by ninjacha** [comment]
to do greentext do \ before your >
\>like this

**Comment by ninjacha** [comment]
anyways, github is autistic some times dont worry about anything i said

**Comment by Koriath** [comment]
Uh... is this suposed to change all those lines?
I mean, like you said, you only buffed sacid and pacid power, it should only be changing line 631, 665, and 674.
There's no conflicts with existing files, so I dunno.

**Comment by newguywhoislearning** [comment]
>Uh... is this suposed to change all those lines?
I've only changed 3 lines, I'm pretty sure about that.
>I mean, like you said, you only buffed sacid and pacid power, it should only be changing line 631, 665, and 674.
>There's no conflicts with existing files, so I dunno.
Perhaps it is because I used the "upload file" feature?Nothing else has been changed though.

**Comment by ZioZan** [comment]
I suggest against merging this because in-hand sprites are broken basically, so guns, spray bottles  don't appear on character sprite in game. Which means this update will increase grief. Maybe later when sprites are fixed.

> Perhaps it is because I used the "upload file" feature?Nothing else has been changed though.

You should not be using this feature, use edit option, or edit files locally and use GitHub to push updates.

**Comment by octareenroon91** [comment]
Yeah, this PR drops the file right in the top directory.  It would pass the compile test fine, since it changes nothing that DreamMaker would look at.

**Pull request closed without merging**
