### PR TITLE
Few Tweaks

### PR DESCRIPTION
**Pull request by Koriath**
Lowered several chances to spawn pests and spread diseases. Replaced
most diseases with innocuous variants based on several presets.

### CODE REVIEW

**Comment by newguywhoislearning** [comment]
What if pest_max was 1?

**Comment by Koriath** [comment]
That's one pest per vent. The limit is rarely reached as of now.
Two vents nearby for instance won't spawn 6 pests. Since they can see each other, the pests they spawn will be in range of the other, and they'll stop at 3.

That bit was intended for when pests roam the station, and the vent is allowed to generate more.
To give a sense of "it's coming from there".

**Comment by Koriath** [comment]
Also terribly sorry about the 8000 lines changed in the map, but aparently the map merger only works when you change tiles.
Changing vars from each tile aparently is not supported.

**Comment by Koriath** [comment]
But sure, what the hell. Having more pests than vents is kind of absurd. I'll change it.

**Comment by octareenroon91** [comment]
What are the var changes on metastation?

**Comment by octareenroon91** [comment]
I wonder if the plague makes ministation more fun.

**Comment by Koriath** [comment]
Can't seem to be able to undo the changes to the map.
Ministation should work out of the box right now, since it uses Areas to determine sanitary zones.
If need be, add more or remove areas from the list.
The system was designed to be universal and work with all maps.
If there's vents, there will be pests.

Haven't really though about other z-levels and Gateway missions. That might be a real danger.

**Comment by Koriath** [comment]
Damnit, tried to replace the map file with the original from Octareen's master.
Ended up with more deletions and new lines. FUCK.

**Comment by octareenroon91** [comment]
Worst case, I'll merge and reset the dmm on master, I guess.

**Comment by octareenroon91** [comment]
Oh, you need to get the RAW dmm file.  It looks like you have an HTML page named `MetaStation/MetaStation.v40D.dmm`

https://github.com/octareenroon91/-tg-station/blob/master/_maps/map_files/MetaStation/MetaStation.v40D.dmm?raw=true

**Pull request merged**
