### PR TITLE
Rechargers and emitters, circuit boards update.

### PR DESCRIPTION
**Pull request by ZioZan**
Added recharger and emitter boards to circuit designs.
Rechagers can now be built and upgraded (Their boards cost gold to make). 
Moved clone pod, clone console, cloning scanner to medical designs.
Moved teleporter console, telepad console to telescience designs.

### CODE REVIEW

**Comment by octareenroon91** [comment]
Does this include cell chargers?

**Comment by ZioZan** [comment]
No, this does not include cell chargers, because those still  would be too slow even with upgrades. Cell chargers are used very rarely. It is much faster to make a new cell, and its cheap too. If we want people to use cell chargers at all, than cells from protolathe and mechfab should not be charged when created. I don't know if that's a good idea.

**Comment by octareenroon91** [comment]
There's a total shitstorm in cell code, so I can live with that rationale.

**Comment by octareenroon91** [comment]
What's changed in stationobjs.dmi?

**Comment by ZioZan** [comment]
> What's changed in stationobjs.dmi?

Added opened recharger icon.

**Pull request merged**
